In [1]:
import numpy as np
array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [4]:
import numpy as np
arr=np.array([0]*5)
print(arr)
print(type(arr))

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

arr2=np.zeros(6,dtype=int)
print(arr2)
print(type(arr2))

[0 0 0 0 0]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[0 0 0 0 0 0]
<class 'numpy.ndarray'>


In [5]:
arr1=np.array([1,2,3,4])
for i in range(0,len(arr1),1):
    print(arr1[i])

1
2
3
4


In [9]:
def resizeArray(arr,new_size):
    # arr2=np.zeros(new_size)
    arr2=np.array([0]*new_size)
    for i in range(len(arr)):
        arr2[i]=arr[i]
    return arr2
arr1=np.array([1,2,3,4])
print(resizeArray(arr1,6))

[1 2 3 4 0 0]


In [15]:
# left shift
def shiftLeft(arr):
    for i in range(1,len(arr),1):
        arr[i-1]=arr[i]
    arr[len(arr)-1]=0
    return arr
arr=np.array([1,2,3,4])
print(shiftLeft(arr))

[2 3 4 0]


In [39]:
name='mihir'
for i in range(1,len(name),1):
    print(name[i])

i
h
i
r


In [41]:
array=[1,2,3,4]
for i in range(1,len(array),1):
    print(array[i])

2
3
4


In [17]:
# right shift
def shiftRight(arr):
    for i in range(len(arr)-1,0,-1):
        arr[i]=arr[i-1]
    arr[0]=0
    return arr
arr=np.array([1,2,3,4])
print(shiftRight(arr))

[0 1 2 3]


In [20]:
def rotateLeft(arr):
    temp=arr[0]
    for i in range(1,len(arr),1):
        arr[i-1]=arr[i]
    arr[len(arr)-1]=temp
    return arr
arr=np.array([1,2,3,4,5])
print(rotateLeft(arr))

[2 3 4 5 1]


In [21]:
def rotateRight(arr):
    temp=arr[len(arr)-1]
    for i in range(len(arr)-1,0,-1):
        arr[i]=arr[i-1]
    arr[0]=temp
    return arr
arr=np.array([1,2,3,4,5])
print(rotateRight(arr))

[5 1 2 3 4]


In [23]:
def reverse_out_of_place(arr):
    arr2=np.zeros(len(arr),dtype=int)
    i=0
    while(i<=len(arr)-1):
        arr2[i]=arr[len(arr)-1-i]
        i+=1
    return arr2
arr=np.array([1,2,3,4,5])
print(reverse_out_of_place(arr))

arr=np.array([10,20,30,40,50,60,70,80,90])
print(reverse_out_of_place(arr))

[5 4 3 2 1]
[90 80 70 60 50 40 30 20 10]


In [ ]:
# def reverse_in_place(arr):
#     x,j=0, len(arr)-1
#     for i in range(len(arr)//2):


In [28]:
def delete_last_element(arr,size):
    if size==0:
        return 'deletion not possible'
    arr[size-1]=0
    return arr
arr=np.zeros(4,dtype=int)
arr[0],arr[1],arr[2]=4,6,5
print(arr)
print(delete_last_element(arr,3))
print(delete_last_element(arr,2))

[4 6 5 0]
[4 6 0 0]
[4 0 0 0]


In [29]:
def delete_any_element(arr,size,index):
    if size==0 or (index<0 and index>=size):
        return 'deletion not possible'
    else:
        for i in range(index,size,1):
            arr[i]=arr[i+1]
        arr[size-1]=0
        return arr
arr=np.zeros(5,dtype=int)
arr[0],arr[1],arr[2],arr[3]=4,6,5,2
print(arr)
print(delete_any_element(arr,4,0))

[4 6 5 2 0]
[6 5 2 0 0]


In [42]:
def discardCards(cards,t):
    
    cards=np.array([10,2,30,2,50,2,2,0,0])
print(discardCards(cards,2))

NameError: name 'cards' is not defined