In [ ]:
import numpy as np
array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [4]:
import numpy as np
def shiftLeft(arr):
    for i in range(1, len(arr), 1):
        arr[i-1]= arr[i]
        arr[len(arr)-1]= 0
    return arr
arr= np.array([1,2,3,4])
print(shiftLeft(arr))

[2 3 0 0]


In [3]:
def resizeArr(arr,new_size):
  new=np.zeros(new_size,dtype=int)
  for i in range(len(arr)):
    new[i]=arr[i]
  return new
arr1=np.array([1,2,3,4,5],dtype=int)
print(resizeArr(arr1,10))

[1 2 3 4 5 0 0 0 0 0]


In [2]:
print('hello')

hello


In [ ]:
def row_rotation(exam_week, seat_status):
  #To Do


seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

In [5]:
import numpy as np
def swap_2columns(m):
    row, col = m.shape
    for i in range(row):
        m[i][0], m[i][i] = m[i][1], m[i][0]
    return m
m=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(m)
print()
print(swap_2columns(m))

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]

[[ 1  2  3  4]
 [ 5  4  6  7]
 [ 8  8  7 10]]


In [6]:
def swap_columns(m):
    row, col = m.shape
    for i in range(row):
        for j in range(col // 2):
            m[i][j], m[i][col - 1 - j] = m[i][col - 1 - j], m[i][j]
    return m
m=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(m)
print()
print(swap_columns(m))

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]

[[ 4  3  2  1]
 [ 7  6  5  4]
 [10  9  8  7]]


In [ ]:
def reverse_Matrix(matrix):
  #TO DO
matrix = np.array([
[14,  8,  0,  4],
[9,  8,  13,  13],
[9,  3,  1,  4],
[2,  10,  13,  6]
])
print(reverse_Matrix(matrix))


the output should be like this
6   13   10  2 
4   1    3   9 
13  13   8   9
4   0    8   14 


In [1]:
import numpy as np

def reverse_Matrix(matrix):
    rows, cols = matrix.shape
    reversed_matrix = np.empty_like(matrix)
    for i in range(rows):
        for j in range(cols):
            reversed_matrix[i, j] = matrix[rows - i - 1, cols - j - 1]
    return reversed_matrix

matrix = np.array([
    [14,  8,  0,  4],
    [9,   8,  13, 13],
    [9,   3,  1,  4],
    [2,  10,  13,  6]
])

reversed_matrix = reverse_Matrix(matrix)
for row in reversed_matrix:
    print(" ".join(map(str, row)))


6 13 10 2
4 1 3 9
13 13 8 9
4 0 8 14


In [3]:
import numpy as np

def reverse_Matrix(matrix):
    rows, cols = matrix.shape
    reversed_matrix = np.zeros(matrix)
    for i in range(rows):
        for j in range(cols):
            reversed_matrix[i, j] = matrix[rows - i - 1, cols - j - 1]
    return reversed_matrix

matrix = np.array([
    [14,  8,  0,  4],
    [9,   8,  13, 13],
    [9,   3,  1,  4],
    [2,  10,  13,  6]
])

reversed_matrix = reverse_Matrix(matrix)
for row in reversed_matrix:
    print(" ".join(map(str, row)))


TypeError: only integer scalar arrays can be converted to a scalar index

In [11]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))

In [14]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\Users\Hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\Users\Hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [16]:
import numpy as np
def reverse_Matrix(matrix):
    rows, cols = matrix.shape
    reversed_matrix = np.zeros((rows, cols), dtype=int)
    for i in range(rows):
        for j in range(cols):
            # reversed_matrix[i, j] = matrix[rows - i - 1, cols - j - 1]
            reversed_matrix[i][j]=matrix[rows-i-1][cols-j-1]

    # reversed_matrix = reverse_Matrix(matrix)
    # for row in reversed_matrix:
    #     print(" ".join(map(str, row)))
    # return reversed_matrix

matrix = np.array([
    [14,  8,  0,  4],
    [9,   8,  13, 13],
    [9,   3,  1,  4],
    [2,  10,  13,  6]
])
print_matrix(matrix)
reversed_matrix = reverse_Matrix(matrix)
print_matrix(reversed_matrix)

|  14 |  8  |  0  |  4  |
-------------------------
|  9  |  8  |  13 |  13 |
-------------------------
|  9  |  3  |  1  |  4  |
-------------------------
|  2  |  10 |  13 |  6  |
-------------------------


AttributeError: 'NoneType' object has no attribute 'shape'

In [18]:
import numpy as np

def row_rotation(exam_week, seat_status):
    # exam_week -= 1
    row, col = seat_status.shape
    new_seat = np.zeros((row, col), dtype=seat_status.dtype)
    for i in range(row):
        for j in range(col):
            new_row_index = (i + exam_week) % row
            new_seat[i][j] = seat_status[new_row_index][j]
    return new_seat

seat_status = np.array([['A', 'B', 'C', 'D', 'E'],
                        ['F', 'G', 'H', 'I', 'J'],
                        ['K', 'L', 'M', 'N', 'O'],
                        ['P', 'Q', 'R', 'S', 'T'],
                        ['U', 'V', 'W', 'X', 'Y'],
                        ['Z', 'AA', 'BB', 'CC', 'DD']])
exam_week = 3
new_seat_status = row_rotation(exam_week, seat_status)
print("Modified seat status after rotation:")
print(new_seat_status)

# Find row number for friend AA
row_number = np.where(new_seat_status == 'AA')[0][0] + 1
print(f'Your friend AA will be on row {row_number}')


Modified seat status after rotation:
[['P' 'Q' 'R' 'S' 'T']
 ['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']
 ['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']]
Your friend AA will be on row 3


In [20]:
import numpy as np

def row_rotation(exam_week, seat_status):
    # exam_week -= 1
    row, col = seat_status.shape
    new_seat = np.empty_like(seat_status, dtype=seat_status.dtype)
    for i in range(row):
        for j in range(col):
            new_row_index = (i + exam_week) % row
            new_seat[i][j] = seat_status[new_row_index][j]
    return new_seat

seat_status = np.array([['A', 'B', 'C', 'D', 'E'],
                        ['F', 'G', 'H', 'I', 'J'],
                        ['K', 'L', 'M', 'N', 'O'],
                        ['P', 'Q', 'R', 'S', 'T'],
                        ['U', 'V', 'W', 'X', 'Y'],
                        ['Z', 'AA', 'BB', 'CC', 'DD']])
exam_week = 3
new_seat_status = row_rotation(exam_week, seat_status)
print("Modified seat status after rotation:")
print(new_seat_status)

# Find row number for friend AA
row_number = np.where(new_seat_status == 'AA')[0][0] + 1
print(f'Your friend AA will be on row {row_number}')


Modified seat status after rotation:
[['P' 'Q' 'R' 'S' 'T']
 ['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']
 ['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']]
Your friend AA will be on row 3


In [21]:
import numpy as np

def reverse_Matrix(matrix):
    rows, cols = matrix.shape
    reversed_matrix = np.zeros((rows, cols), dtype=int)
    
    # Reversing the matrix without using default functions
    for i in range(rows):
        for j in range(cols):
            reversed_matrix[i, j] = matrix[rows - i - 1, cols - j - 1]
            reversed_matrix[i, j] = matrix[1,2]
    return reversed_matrix

matrix = np.array([
    [14,  8,  0,  4],
    [9,  8,  13,  13],
    [9,  3,  1,  4],
    [2,  10,  13,  6]
])
reversed_matrix = reverse_Matrix(matrix)
print(reversed_matrix)


[[ 6 13 10  2]
 [ 4  1  3  9]
 [13 13  8  9]
 [ 4  0  8 14]]


In [6]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))



In [17]:
# import numpy as np

# def row_rotation(exam_week, seat_status):
#     row, col = seat_status.shape
#     new_seat = np.zeros((row, col), dtype=object)
    
#     for i in range(row):
#         for j in range(col):
#             current_seat = seat_status[i][j]
#             # Calculate the new row number based on the rotation policy
#             new_row = (i+exam_week-1)%row
#             new_seat[new_row][j] = current_seat
            
#             # If the current seat belongs to "AA", store its new row number
#             if current_seat=='AA':
#                 row_number=new_row
                
#     # Print the seat status for the given exam week
#     print_matrix(new_seat)
    
#     # Return the row number where "AA" will be seated
#     return row_number

# # print_matrix(seat_status)
#     # for row in matrix:
#     #     print(" ".join(str(cell) for cell in row))

# # Example usage
# seat_status = np.array([
#     ['A', 'B', 'C', 'D', 'E'],
#     ['F', 'G', 'H', 'I', 'J'],
#     ['K', 'L', 'M', 'N', 'O'],
#     ['P', 'Q', 'R', 'S', 'T'],
#     ['U', 'V', 'W', 'X', 'Y'],
#     ['Z', 'AA', 'BB', 'CC', 'DD']
# ])

# exam_week = 3
# print_matrix(seat_status)
# print()
# row_number = row_rotation(exam_week, seat_status)
# print(f'Your friend AA will be on row {row_number}')


In [24]:
import numpy as np

def row_rotation(exam_week, seat_status):
    row, col = seat_status.shape
    new_seat = np.zeros((row, col), dtype=object)
    
    for i in range(row):
        for j in range(col):
            current_seat = seat_status[i][j]
            # Calculate the new row number based on the rotation policy
            new_row = (i + exam_week - 1) % row
            new_seat[new_row][j] = current_seat
            
            # If the current seat belongs to "AA", store its new row number
            if current_seat == 'AA':
                row_number = new_row
                
    # Print the seat status for the given exam week
    print_matrix(new_seat)
    
    # Return the row number where "AA" will be seated
    return row_number

seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}')

|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------

|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------
|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
Your friend AA will be on row 1


In [29]:
import numpy as np

def row_rotation(exam_week, seat_status):
    exam_week-=1
    row, col = seat_status.shape
    
    for i in range(row):
        for j in range(col):
            if seat_status[i][j]=='AA':
                frnd=i
                break
    frnd=(frnd+exam_week)%(row-1)
    for i in range(exam_week):
            for j in range(row-1,0,-1):
                temp=seat_status[j].copy()
                seat_status[j]=seat_status[j-1]
                seat_status[j-1]=temp
    print(seat_status)
    return frnd

seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}')

|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------

[['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']
 ['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['P' 'Q' 'R' 'S' 'T']]
Your friend AA will be on row 2


In [52]:
import numpy as np

def row_rotation(exam_week, seat_status):
    exam_week -= 1
    row, col = seat_status.shape
    
    for i in range(row):
        for j in range(col):
            if seat_status[i][j] == 'AA':
                frnd = i
                break
                
    for _ in range(exam_week):
        temp = np.zeros(col, dtype='object')
        for i in range(row - 1, 0, -1):
            for k in range(col):
                temp[k] = seat_status[i][k]
                seat_status[i][k] = seat_status[i - 1][k]
                seat_status[i - 1][k] = temp[k]
    
    frnd = (frnd + exam_week) % row  # Adjusting frnd after rotation
        
    print(seat_status)
    return frnd

seat_status = np.array([
    ['A', 'B', 'C', 'D', 'E'],
    ['F', 'G', 'H', 'I', 'J'],
    ['K', 'L', 'M', 'N', 'O'],
    ['P', 'Q', 'R', 'S', 'T'],
    ['U', 'V', 'W', 'X', 'Y'],
    ['Z', 'AA', 'BB', 'CC', 'DD']
])

exam_week = 3
print(seat_status)
print()
row_number = row_rotation(exam_week, seat_status)  # This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}')


[['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['P' 'Q' 'R' 'S' 'T']
 ['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']]

[['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']
 ['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['P' 'Q' 'R' 'S' 'T']]
Your friend AA will be on row 1


In [54]:
import numpy as np
def row_rotation(exam_week, seat_status):
    row,col=seat_status.shape
    frnd=(frnd+exam_week)%(row-1)
    for i in range(exam_week):
            for j in range(row-1,0,-1):
                temp=seat_status[j]
                seat_status[j]=seat_status[j-1]
                seat_status[j-1]=temp
    print(seat_status)
    friend_row=0
    for i in range(row):
        for j in range(col):
            if seat_status[i][j]=="AA":
                friend_row=i+1
                break
    return friend_row
seat_status = np.array([
    ['A', 'B', 'C', 'D', 'E'],
    ['F', 'G', 'H', 'I', 'J'],
    ['K', 'L', 'M', 'N', 'O'],
    ['P', 'Q', 'R', 'S', 'T'],
    ['U', 'V', 'W', 'X', 'Y'],
    ['Z', 'AA', 'BB', 'CC', 'DD']
])
exam_week = 3
print(seat_status)
print()
row_number = row_rotation(exam_week, seat_status)
print(f'Your friend AA will be on row {row_number}')

[['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['P' 'Q' 'R' 'S' 'T']
 ['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']]



UnboundLocalError: cannot access local variable 'frnd' where it is not associated with a value