In [2]:
import numpy as np

array to new array

In [115]:
def arrToNewArr(arr):
    newArr=np.zeros(len(arr),dtype=int)
    index=0
    for i in range(len(newArr)):
        # newArr[i]+=arr[i]
        newArr[index]+=arr[i]   # index = 0 is the right way to do this thing
        index+=1
    print(newArr)
arr=[1,2,3,4,5,6,7,8]
arrToNewArr(arr)

[1 2 3 4 5 6 7 8]


## **2D ARRAY**

2D to array

In [16]:
def twodToArr(matrix):
    row,col=matrix.shape
    arr=np.zeros((row*col),dtype=int)
    # don't need to use a third for loop here just take a variable and update it and that's your index number 
    index=0
    for i in range(row):
        for j in range(col):
            arr[index]+=matrix[i][j]
            index+=1
    print(arr)
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)
twodToArr(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


row wise sum

In [39]:
def rowSum(matrix):
    row,col=matrix.shape
    arr=np.zeros((row,1),dtype=int) # row = 3, 1 because in every column there should 1 row if that makes sense
    for i in range(row):
        for j in range(col):
            # sum+=matrix[i][j] this gives the entire sum (every number)
            arr[i][0]+=matrix[i][j]
    print(arr)
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)
rowSum(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[10]
 [26]
 [42]]


column wise sum

In [41]:
def colSum(matrix):
    row,col=matrix.shape
    arr=np.zeros((1,col),dtype=int) # row = 3, 1 because in every column there should 1 row if that makes sense
    for i in range(row):
        for j in range(col):
            # sum+=matrix[i][j] this gives the entire sum (every number)
            arr[0][j]+=matrix[i][j]
    print(f'ouput: {arr}')
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)
colSum(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ouput: [[15 18 21 24]]


flip down and up wise

In [81]:
def upDownFlip(matrix):
    row,col=matrix.shape
    for i in range(row//2):
        for j in range(col):
            temp=matrix[i][j]
            matrix[i][j]=matrix[row-i-1][j]
            matrix[row-i-1][j]=temp
    print(matrix)
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)
print('output:')
upDownFlip(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
output:
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [62]:
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row,col=matrix.shape
print(matrix,row,col)
print(matrix[row-1][col-1]) # this gives the last elements

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 3 4
12


flip right to left wise

In [82]:
def leftRightFlip(matrix):
    row,col=matrix.shape
    for i in range(row):
        for j in range(col//2):
            temp=matrix[i][j]
            matrix[i][j]=matrix[i][col-j-1]
            matrix[i][col-j-1]=temp
    print(matrix)
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)
print('output:')
leftRightFlip(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
output:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


diagonal sum

In [83]:
def digSum(matrix):
    sum=0
    row,col=matrix.shape
    for i in range(row):
        sum+=matrix[i][i]
    print(sum)
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
digSum(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


find min

In [106]:
def findMin(matrix):
    row,col=matrix.shape
    minVal=matrix[0][0]
    for i in range(row):
        for j in range(col):
            if matrix[i][j]<minVal:
                minVal=matrix[i][j]
    print(minVal)
matrix=np.array([[16,2,3],[4,1,6],[7,8,9]])
print(matrix)
findMin(matrix)

[[16  2  3]
 [ 4  1  6]
 [ 7  8  9]]
1


find max

In [109]:
def findMax(matrix):
    row,col=matrix.shape
    maxVal=matrix[0][0]
    for i in range(row):
        for j in range(col):
            if matrix[i][j]>maxVal:
                maxVal=matrix[i][j]
    print(maxVal)
matrix=np.array([[16,2,3],[100,5,60],[7,8,9]])
print(matrix)
findMax(matrix)

[[ 16   2   3]
 [100   5  60]
 [  7   8   9]]
100


adding two matrix

In [3]:
def addMatrix(m,n):
    row_m,col_m=m.shape
    row_n,col_n=n.shape
    if row_m==row_n and col_m==col_n:
        print('Mismatch of dimention')
    result=np.zeros((row_m,col_m),dtype=int)
    for i in range(row_m):
        for j in range(col_m):
            result[i][j]=m[i][j]+n[i][j]
    return result
m=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
n=np.array([[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(m)
print('+')
print(n)
print(addMatrix(m,n))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
+
[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
Mismatch of dimention
[[17 19 21 23 25]
 [27 29 31 33 35]
 [37 39 41 43 45]]


multiplying two matrix

In [5]:
def multiply_matrix(m,n):
    row_m,col_m=m.shape
    row_n,col_n=n.shape
    if col_m==row_n:
        row,col=row_m,col_n
        result=np.zeros((row,col),dtype=int)
        for i in range(row):
            for j in range(col):
                for k in range(col_m):
                    result[i][j]+=m[i][k]*n[k][j]
        return result
m=np.random.randint(9,size=(3,4))
n=np.random.randint(8,size=(4,3))
print(m)
print('x')
print(n)
print('Result:')
print(multiply_matrix(m,n))

[[3 0 8 7]
 [6 4 8 8]
 [2 4 1 6]]
x
[[6 4 1]
 [6 2 0]
 [1 5 6]
 [1 3 4]]
Result:
[[33 73 79]
 [76 96 86]
 [43 39 32]]


## **LINKED LIST**

In [6]:
class Node:
    def __init__(self,elem,next=None,prev=None):
        self.elem=elem;self.next=next;self.prev=prev

creating a LL from an array

In [7]:
def createLL(arr):
    head=Node(arr[0],None,None)
    temp=head
    for i in range(1,len(arr)):
        newNode=Node(arr[i],None,None)
        temp.next=newNode
        newNode.prev=temp
        temp=newNode
    temp=temp.next
    return head
arr=[1,2,3,4,5,6,7,8]
h=createLL(arr)

printing the LL

In [8]:
def printLL(head):
    temp=head
    while temp!=None:
        if temp.next!=None:
            print(temp.elem,end='--->')
        else:
            print(temp.elem)
        temp=temp.next
h=createLL(arr)
printLL(h)

1--->2--->3--->4--->5--->6--->7--->8


node at

In [54]:
# node at given index ---> elem
def nodeAt(head,idx):
    count=0
    temp=head
    output=None
    while temp!=None:
        if count==idx:
            output=temp
            break
        else:
            count+=1
        temp=temp.next
    if output==None:
        print('Invalid')
    else:
        return output.elem
printLL(h)
print(nodeAt(h,3))

1--->2--->3--->4--->5--->6--->7--->8
4


In [47]:
def indexOf(head,elem):
    current_node=head
    count=0
    while current_node!=None:
        if current_node.elem==elem:
            return count
        count+=1
        current_node=current_node.next
    return f'There is not such element in the linked list'
arr=np.array([10,20,53,84,75,76,97,21,90,15]) # Defining an array
mod_h=createLL(arr) # Creating a Link List
print(indexOf(mod_h,85))
print(indexOf(mod_h,84))
# printList(h)

There is not such element in the linked list
3


append

In [12]:
def append(head,val):
    temp=head
    while temp.next!=None:
        temp=temp.next
    newNode=Node(val,None,None)
    temp.next=newNode
    return head
printLL(append(h,15))

1--->2--->3--->4--->5--->6--->7--->8--->15


In [16]:
def append(head,val):   # for doubly linked list ---> append
    temp=head
    while temp.next!=None:
        temp=temp.next
    newNode=Node(val,None,None)
    temp.next=newNode
    newNode.prev=temp   # just 1 line different
    return head
printLL(append(h,15))

1--->2--->3--->4--->5--->6--->7--->8--->15


In [ ]:
def append(head,val):   # for doubly CIRCULAR linked list ---> append
    temp=head
    while temp.next!=head:
        temp=temp.next
    newNode=Node(val,None,None)
    temp.next=newNode
    newNode.next=head   # to make it circular
    newNode.prev=temp   # just 1 line different
    head.prev=newNode
    return head
printLL(append(h,15))

In [ ]:
# the concept is correct here but for some reason it's not working

In [ ]:
def append(head, val):
  """Appends a new node with the value 'val' to the end of a doubly circular linked list."""
  if head is None:
    return Node(val)

  temp = head
  while temp.next != head:
    temp = temp.next

  newNode = Node(val)
  temp.next = newNode
  newNode.next = head

  newNode.prev = temp
  head.prev = newNode

  return head
printLL(append(h,85))

prepend

In [191]:
def prepend(head,val):
    newNode=Node(val,None,None)
    newNode.next=head
    return newNode
printLL(prepend(h,25))

25--->1--->2--->3--->4--->5--->6--->7--->8--->15


In [17]:
def prepend(head,val):  # for doubly linked list ---> prepend
    newNode=Node(val,None,None)
    newNode.next=head
    head.prev=newNode   # difference
    return newNode
printLL(prepend(h,25))

25--->1--->2--->3--->4--->5--->6--->7--->8--->15


In [ ]:
def prepend(head,val):  # for doubly CIRCULAR linked list ---> prepend
    newNode=Node(val,None,None)
    newNode.next=head
    head.prev=newNode   # difference
    temp=head
    while temp.next!=newNode:
        temp=temp.next
    temp.next=newNode
    newNode.prev=temp
    return newNode
printLL(prepend(h,25))

insert

In [192]:
def insert(head,idx,val):
    temp=head
    count=0
    while count!=idx:
        temp=temp.next
        count+=1
    newNode=Node(val,None,None)
    newNode.next=temp.next
    temp.next=newNode
    return head
printLL(insert(h,3,150))

1--->2--->3--->4--->150--->5--->6--->7--->8--->15


In [22]:
def insert(head,idx,val):   # for doubly linked list ---> insert
    temp=head
    count=0
    while count!=idx:
        temp=temp.next
        count+=1
    newNode=Node(val,None,None)
    newNode.next=temp.next
    temp.next=newNode
    temp.next.prev=newNode  # this line 
    newNode.prev=temp       # this line
    return head
printLL(insert(h,4,330))

1--->2--->3--->4--->5--->330--->6--->7--->8


delete

In [193]:
def delete(head,idx):
    temp=head
    count=0
    while count!=idx-1:
        temp=temp.next
        count+=1
    temp.next=temp.next.next
    return head
printLL(delete(h,4))

1--->2--->3--->4--->5--->6--->7--->8--->15


In [23]:
def delete(head,idx):   # for doubly linked list ---> delete
    temp=head
    count=0
    while count!=idx-1:
        temp=temp.next
        count+=1
    temp.next=temp.next.next
    t1=temp.next.next   # this line
    t1.prev=temp        # this line
    return head
printLL(delete(h,4))

1--->2--->3--->4--->330--->6--->7--->8


In [194]:
print('Original array:')
printLL(createLL(arr))  # so whatever changes made --- it doesn't really affect the original array (stores the changes in h)

Original array:
1--->2--->3--->4--->5--->6--->7--->8


dummy head doubly LL

In [69]:
def createDummyLL(arr):
    dh=Node(None,None,None)
    dh.next=dh
    dh.prev=dh
    temp=dh
    for i in range(len(arr)):
        newNode=Node(arr[i],dh,temp)
        temp.next=newNode
        temp=temp.next
        dh.prev=temp
    return dh
arr=[1,2,3,4,5,6,7,8]
v=createDummyLL(arr)

printing dummy head doubly LL

In [70]:
def printDummyLL(dh):
  temp = dh.next
  while temp != dh:
    if temp.next != dh:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()
printDummyLL(v)

1-->2-->3-->4-->5-->6-->7-->8



insert in doubly circular LL

In [ ]:
# def insertDoublyLL(head,idx,elem):
#     new_node = Node(elem)
#     if idx == 0:
#         new_node.next = head
#         if head:
#             head.prev = new_node
#         return new_node

#     current = head
#     count = 0
#     while current.next and count < idx - 1:
#         current = current.next
#         count += 1

#     if count != idx - 1:
#         print("Index out of bounds.")
#         return head

#     new_node.next = current.next
#     new_node.prev = current
#     if current.next:
#         current.next.prev = new_node
#     current.next = new_node

#     return head
# m=insertDoublyLL(h,4,150)
# printLL(m)
# printDummyLL(m)

In [78]:
def change_LL(head):
    count = 0
    temp = head
    while temp!=None:
        count += 1
        temp = temp.next
    # print(count)
    mid = count // 2
    temp = head
    for i in range(mid-1):
        temp = temp.next
    second_LL = temp.next
    temp.next = None

    printLL(head)
    print("\nSecond LL")
    printLL(second_LL)
    print("After reverse")
    head = reverse_LL(head)
    printLL(head)

    temp = head
    while temp.next != None:
        temp = temp.next
    temp.next = second_LL
    print("After merge")    # this is the important part
    printLL(head)

change_LL(h)

1--->2--->3--->4

Second LL
5--->6--->7--->8
After reverse
1
4--->3--->2--->1
After merge
4--->3--->2--->1--->5--->6--->7--->8


reverse

In [66]:
def reverse_LL(head):
    head2=Node(head.elem,None)
    printLL(head2)
    temp=head.next
    while temp!=None:
        newNode=Node(temp.elem,None)
        newNode.next=head2
        head2=newNode
        temp=temp.next
    return head2
r=reverse_LL(h)
printLL(r)

1
8--->7--->6--->5--->150--->150--->4--->3--->2--->1
