In [1]:
import numpy as np

In [12]:
# left shift
def leftShift(arr):
    for i in range(1,len(arr)):
        arr[i-1]=arr[i]
    arr[len(arr)-1]=0
    return arr
arr=np.array([1,2,3,4,5])
print(leftShift(arr))

[2 3 4 5 0]


In [13]:
# right shift
def rightShift(arr):
    for i in range(len(arr)-1,0,-1):
        arr[1]=arr[i-1]
    arr[0]=0
    return arr
arr=np.array([1,2,3,4,5])
print(rightShift(arr))

[0 1 3 4 5]


In [14]:
# left rotate
def leftRotate(arr):
    temp=arr[0]
    for i in range(1,len(arr)):
        arr[i-1]=arr[i]
    arr[len(arr)-1]=temp
    return arr
arr=np.array([1,2,3,4,5])
print(leftRotate(arr))

[2 3 4 5 1]


In [11]:
# right rotate
def rigthRotate(arr):
    temp=arr[len(arr)-1]
    for i in range(len(arr)-1,0,-1):
        arr[i]=arr[i-1]
    arr[0]=temp
    return arr
arr=np.array([1,2,3,4,5])
print(rigthRotate(arr))

[5 1 2 3 4]


In [18]:
def reverseArrayInPlace(arr):
    i=0
    j=len(arr)-1
    while i<j:
        temp=arr[i]
        arr[i]=arr[j]
        arr[j]=temp
        i+=1
        j-=1
    return arr
arr=np.array([1,2,3,4,5])
print(reverseArrayInPlace(arr))

[5 4 3 2 1]


In [21]:
def findlow(arr):
    minVal=arr[0]
    for i in range(len(arr)):
        if arr[i]<minVal:
            minVal=arr[i]
    return minVal
arr=np.array([1,2,3,4,5])
print(findlow(arr))

1


In [27]:
def findhigh(arr):
    maxVal=arr[0]
    for i in range(len(arr)):
        if arr[i]>maxVal:
            maxVal=arr[i]
    return maxVal
arr=np.array([10,2,3,4,5])
print(findhigh(arr))

10


In [52]:
def insertElement(arr,size,element,idx):
    if size==len(arr) or size>len(arr):
        print('No space left')
    else:
        for i in range(size,idx,-1):
            arr[i]=arr[i-1]
        arr[idx]=element
    return arr
arr=np.array([6,7,8,9,15])
print(insertElement(arr,1,85,3))

[ 6  7  8 85 15]


In [53]:
# row wise sum
def sumOfrow(arr):
    row,col=arr.shape
    result=np.zeros((row,1),dtype=int)
    for i in range(row):
        for j in range(col):
            result[i][0]+=arr[i][j]
    return result
arr=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(sumOfrow(arr))

[[ 15]
 [150]]


In [63]:
# column wise sum
def sumOfcolumn(arr):
    row,col=arr.shape
    newArr=np.zeros((1,col),dtype=int)
    for i in range(col):
        for j in range(row):
            newArr[0][i]+=arr[j][i]
    return newArr
arr=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(sumOfcolumn(arr))

[[11 22 33 44 55]]


In [7]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))



In [71]:
# swap columns
def swap_columns(arr):
    row,col=arr.shape
    for i in range(row):
        for j in range(col//2):
            arr[i][j],arr[i][col-1-j]=arr[i][col-1-j],arr[i][j]
    return arr
arr=np.array([[4,3,8],[2,5,-1],[-6,16,9],[4,13,11]])
print_matrix(arr)
print()
print('flipped')
print()
print_matrix(swap_columns(arr))

|  4  |  3  |  8  |
-------------------
|  2  |  5  |  -1 |
-------------------
|  -6 |  16 |  9  |
-------------------
|  4  |  13 |  11 |
-------------------

flipped

|  8  |  3  |  4  |
-------------------
|  -1 |  5  |  2  |
-------------------
|  9  |  16 |  -6 |
-------------------
|  11 |  13 |  4  |
-------------------


In [9]:
def flip_vertical(matrix):
    row,col=matrix.shape
    for i in range(row//2):
        for j in range(col):
            temp=matrix[i][j]
            matrix[i][j]=matrix[row-1-i][j]
            matrix[row-1-i][j]=temp
    return matrix

def flip_horizontal(matrix):
    row,col=matrix.shape
    for i in range(row):
        for j in range(col//2):
            temp=matrix[i][j]
            matrix[i][j]=matrix[i][col-1-j]
            matrix[i][col-1-j]=temp
    return matrix

def reverse_Matrix(matrix):
    #TO DO
    flip_vertical(matrix)
    flip_horizontal(matrix)
    return matrix

matrix = np.array([
[14,  8,  0,  4],
[9,  8,  13,  13],
[9,  3,  1,  4],
[2,  10,  13,  6]
])
print_matrix(matrix)
print()
reversed_matrix = reverse_Matrix(matrix)
print_matrix(reversed_matrix)

#This should print
#|  6  |  13 |  10 |  2  |
#-------------------------
#|  4  |  1  |  3  |  9  |
#-------------------------
#|  13  |  13  |  8 |  9 |
#-------------------------
#|  4 |  0  |  8  |  14  |
#-------------------------

|  14 |  8  |  0  |  4  |
-------------------------
|  9  |  8  |  13 |  13 |
-------------------------
|  9  |  3  |  1  |  4  |
-------------------------
|  2  |  10 |  13 |  6  |
-------------------------

|  6  |  13 |  10 |  2  |
-------------------------
|  4  |  1  |  3  |  9  |
-------------------------
|  13 |  13 |  8  |  9  |
-------------------------
|  4  |  0  |  8  |  14 |
-------------------------


In [6]:
# def flip_vertical(matrix):
#     row,col=matrix.shape
#     for i in range(row//2):
#         for j in range(col):
#             temp=matrix[i][j]
#             matrix[i][j]=matrix[row-1-i][j]
#             matrix[row-1-i][j]=temp
#     return matrix

# def flip_horizontal(matrix):
#     row,col=matrix.shape
#     for i in range(row):
#         for j in range(col//2):
#             temp=matrix[i][j]
#             matrix[i][j]=matrix[i][col-1-j]
#             matrix[i][col-1-j]=temp
#     return matrix

def reverse_Matrix(matrix):
    #TO DO
    row,col=matrix.shape
    for i in range(row//2):
        for j in range(col):
            temp=matrix[i][j]
            matrix[i][j]=matrix[row-1-i][j]
            matrix[row-1-i][j]=temp
    for i in range(row):
        for j in range(col//2):
            temp=matrix[i][j]
            matrix[i][j]=matrix[i][col-1-j]
            matrix[i][col-1-j]=temp
    return matrix

matrix = np.array([
[14,  8,  0,  4],
[9,  8,  13,  13],
[9,  3,  1,  4],
[2,  10,  13,  6]
])
# print_matrix(matrix)
reversed_matrix = reverse_Matrix(matrix)
print(reversed_matrix)

#This should print
#|  6  |  13 |  10 |  2  |
#-------------------------
#|  4  |  1  |  3  |  9  |
#-------------------------
#|  13  |  13  |  8 |  9 |
#-------------------------
#|  4 |  0  |  8  |  14  |
#-------------------------

[[ 6 13 10  2]
 [ 4  1  3  9]
 [13 13  8  9]
 [ 4  0  8 14]]


In [2]:
import numpy as np
def reverse_Matrix(matrix):
    #TO DO
    row, col = matrix.shape
    for i in range(row//2):
        for j in range(col):
            temp = matrix[i][j]
            matrix[i][j] = matrix[row-1-i][j]
            matrix[row-1-i][j] = temp
            
            if j < col//2:  # Only perform swapping if j is within the first half of the columns
                temp = matrix[i][j]
                matrix[i][j] = matrix[i][col-1-j]
                matrix[i][col-1-j] = temp
    # flip_vertical(matrix)
    # flip_horizontal(matrix)
    return matrix

matrix = np.array([
[14,  8,  0,  4],
[9,  8,  13,  13],
[9,  3,  1,  4],
[2,  10,  13,  6]
])
# print_matrix(matrix)
reversed_matrix = reverse_Matrix(matrix)
print(reversed_matrix)

[[ 4  0 13  6]
 [13 13  1  4]
 [ 9  8  3  9]
 [14  8 10  2]]


In [76]:
import numpy as np

def reverse_Matrix(matrix):
    row, col = matrix.shape
    for i in range(row // 2):
        for j in range(col):
            # Flip vertically
            temp = matrix[i, j]
            matrix[i, j] = matrix[row - 1 - i, j]
            matrix[row - 1 - i, j] = temp
            
        for j in range(col // 2):
            # Flip horizontally
            temp = matrix[i, j]
            matrix[i, j] = matrix[i, col - 1 - j]
            matrix[i, col - 1 - j] = temp
            
    return matrix

matrix = np.array([
    [14,  8,  0,  4],
    [9,  8,  13,  13],
    [9,  3,  1,  4],
    [2,  10,  13,  6]
])

reversed_matrix = reverse_Matrix(matrix)
print(reversed_matrix)


[[ 6 13 10  2]
 [ 4  1  3  9]
 [ 9  8 13 13]
 [14  8  0  4]]


In [29]:
def calculation(amount,days,duration):
    output=amount*days*duration
    return f'You have saved {output} tk'
print(calculation(100,30,5))
print(calculation(100,30,12))
print(calculation(150,30,12))
print(calculation(150,30,1))

You have saved 15000 tk
You have saved 36000 tk
You have saved 54000 tk
You have saved 4500 tk


In [9]:
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\Users\Hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\Users\Hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [11]:
#Run this cell
class Node:
  def __init__(self,elem,next = None):
    self.elem,self.next = elem,next

def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head

def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()


In [15]:
def check_similar(building_1, building_2):
  cur1 = building_1
  cur2 = building_2

  # Traverse both linked lists simultaneously
  while cur1 is not None and cur2 is not None:
    if cur1.elem == cur2.elem:
      # If elements at current positions are equal, continue to next nodes
      cur1 = cur1.next
      cur2 = cur2.next
    else:
      # If elements at current positions are not equal, return 'not similar'
      return 'Not Similar'

  # If both linked lists have been traversed completely and both have reached the end, they are similar
  if cur1==None and cur2==None:
    return 'Similar'
  else:
    # If one list is longer than the other, they are not similar
    return 'Not Similar'
print('==============Test Case 1=============')
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
building_2 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
print('Building 1: ', end = ' ')
printLinkedList(building_1)
print('Building 2: ', end = ' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value) #This should print 'Similar'
unittest.output_test(returned_value, 'Similar')
print()

print('==============Test Case 2=============')
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Yellow', 'Green']))
building_2 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
print('Building 1: ', end = ' ')
printLinkedList(building_1)
print('Building 2: ', end = ' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value) #This should print 'Not Similar'
unittest.output_test(returned_value, 'Not Similar')
print()

print('==============Test Case 3=============')
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
building_2 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green', 'Blue']))
print('Building 1: ', end = ' ')
printLinkedList(building_1)
print('Building 2: ', end = ' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value) #This should print 'Not Similar'
unittest.output_test(returned_value, 'Not Similar')
print()

print('==============Test Case 4=============')
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green', 'Blue']))
building_2 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
print('Building 1: ', end = ' ')
printLinkedList(building_1)
print('Building 2: ', end = ' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value) #This should print 'Not Similar'
unittest.output_test(returned_value, 'Not Similar')
print()

==============Test Case 1=============
Building 1:  Red-->Green-->Yellow-->Red-->Blue-->Green

Building 2:  Red-->Green-->Yellow-->Red-->Blue-->Green

None
None
Similar
Accepted

==============Test Case 2=============
Building 1:  Red-->Green-->Yellow-->Red-->Yellow-->Green

Building 2:  Red-->Green-->Yellow-->Red-->Blue-->Green

Not Similar
Accepted

==============Test Case 3=============
Building 1:  Red-->Green-->Yellow-->Red-->Blue-->Green

Building 2:  Red-->Green-->Yellow-->Red-->Blue-->Green-->Blue

None
Not Similar
Accepted

==============Test Case 4=============
Building 1:  Red-->Green-->Yellow-->Red-->Blue-->Green-->Blue

Building 2:  Red-->Green-->Yellow-->Red-->Blue-->Green

None
Not Similar
Accepted



In [4]:
class Node:
    def __init__(self, elem=None, next=None):
        self.elem = elem
        self.next = next

class Stack:
    def __init__(self):
        self.__top = None

    def push(self, elem):
        nn = Node(elem, self.__top)
        self.__top = nn

    def pop(self):
        if self.__top is None:
            return None
        e = self.__top
        self.__top = self.__top.next
        return e.elem

    def peek(self):
        if self.__top is None:
            return None
        return self.__top.elem

    def isEmpty(self):
        return self.__top is None
    
    def print_stack(st):
        if st.isEmpty():
            return
        p = st.pop()
        print('|',p,end=' ')
        if p<10:
            print(' |')
        else:
            print('|')

    

def diamond_count(stack, string):
    diamonds = 0
    for char in string:
        if char == '<':
            stack.push(char)
            print_stack(stack)
        elif char == '>' and stack.peek() == '<':
            stack.pop()
            diamonds += 1
    return diamonds

# Test cases
print('Test 01')
stack = Stack()
string = '<..><.<..>> '
returned_value = diamond_count(stack, string)
print(f'Number of Diamonds: {returned_value}')  # This should print 3
print('-----------------------------------------')

print('Test 02')
stack = Stack()
string = '<<<..<......<<<<....>'
returned_value = diamond_count(stack, string)
print(f'Number of Diamonds: {returned_value}')  # This should print 1
print('-----------------------------------------')

print('Test 03')
stack = Stack()
string = '>>><...<<..>>...>...>>>'
returned_value = diamond_count(stack, string)
print(f'Number of Diamonds: {returned_value}')  # This should print 3
print('-----------------------------------------')


Test 01


NameError: name 'print_stack' is not defined