In [ ]:
# from the basic topics
# 1. Array
# 2. Multidimentional Array
# 3. Linked List
# 4. Doubly Linked List
# 5. Stack
# 6. Queue

Linked List

In [1]:
import numpy as np
class Node:
    def __init__(self,elem,next):
        self.elem=elem
        self.next=next

In [11]:
# creating a list
def createList(arr):
    head=Node(arr[0],None)
    tail=head
    for i in range(1,len(arr)):
        newNode=Node(arr[i],None)
        tail.next=newNode   # linking the nodes
        tail=tail.next  # update the tail
    return head
arr=np.array([1,2,3,4,5,6])
h=createList(arr)
# printing the list
def printList(head):
    temp_node=head
    while temp_node!=None:
        if temp_node.next!=None:
            print(temp_node.elem,end='--->')
        else:
            print(temp_node.elem)
        temp_node=temp_node.next    # setting the next value to current node
    print()
printList(h)

1--->2--->3--->4--->5--->6



In [12]:
# counting
def countList(head):
    count=0
    temp=head
    while temp!=None:
        count+=1
        temp=temp.next
    return count
print(countList(h))

6


In [17]:
# node at given index ---> elem
def nodeAt(head,idx):
    count=0
    temp=head
    output=None
    while temp!=None:
        if count==idx:
            output=temp
            break
        else:
            count+=1
        temp=temp.next
    if output==None:
        print('Invalid')
    else:
        return output.elem
print(nodeAt(h,3))

4


In [20]:
# elem at   ---> array: [1,2,3,4,5] so in 3 no. index the element is 4
def elemAt(head,idx):
    count=0
    temp=head
    while temp!=None:
        if temp.next!=None:
            if count==idx:
                return temp.elem
            temp=temp.next
            count+=1
        else:
            return 'out of range'
    return None
print(elemAt(h,3))

4


In [24]:
# search index
def searchIdx(head,elem):
    temp=head
    count=0
    while temp!=None:
        if temp.elem==elem:
            return count
        else:
            count+=1
        temp=temp.next
    return 'no such element'
print(searchIdx(h,1))

0


In [29]:
# inserting an elem
def insert(head,idx,elem):
    count=0
    temp=head
    is_updated=False
    while temp!=None:
        if count==idx:
            temp.elem=elem
            is_updated=True
            break
        temp=temp.next
        count+=1
    if is_updated:
        print('successfully added')
    else:
        print('invalid index')
printList(insert(h,2,56))
printList(h)

successfully added

1--->2--->56--->4--->5--->56



In [5]:
#Assignment Part 1
class Patient:
  #write a constructor
  def __init__(self,id,name,age,bloodgroup,prev=None,next=None):
    self.id=id
    self.name=name
    self.age=age
    self.bloodgroup=bloodgroup
    self.prev=prev
    self.next=next
class WRM:
    def __init__(self):
        self.dummy_head=Patient(None, None, None, None)
        self.dummy_head.next=self.dummy_head
        self.dummy_head.prev=self.dummy_head
        self.tail=self.dummy_head

    def registerPatient(self,id,name,age,bloodgroup):
        new_patient=Patient(id,name,age,bloodgroup,self.tail,self.dummy_head)
        self.tail.next=new_patient
        self.dummy_head.prev=new_patient
        self.tail=new_patient

    def servePatient(self):
        if self.dummy_head.next==self.dummy_head:
            print("No patients to serve.")
        else:
          serving_patient=self.dummy_head.next
          self.dummy_head.next=serving_patient.next
          serving_patient.next.prev=self.dummy_head
          print(f'Serving patient: {serving_patient.name}')

    def showAllPatient(self):
        temp=self.dummy_head.next
        while temp!=self.dummy_head:
            print(f'Patient ID: {temp.id} Name: {temp.name} Bloodgroup: {temp.bloodgroup}')
            temp = temp.next

    def canDoctorGoHome(self):
        if self.dummy_head.next==self.dummy_head:
            print('Yes, doctor can go home.')
        else:
            print('No, doctor cannot go home.')

    def cancelAll(self):
        self.dummy_head.next=self.dummy_head
        self.dummy_head.prev=self.dummy_head
        print('All appointments canceled.')

    def ReverseTheLine(self):
        temp=self.dummy_head.next
        self.dummy_head.prev=self.dummy_head.next
        while temp!=self.dummy_head:
            t=temp
            temp=temp.next
            next=t.next
            prev=t.prev
            t.next=prev
            t.prev=next
        self.dummy_head.next=t
        print('Reverse successfull!')
# Instantiate the waiting room manager
waiting_room = WRM()

# Register patients
waiting_room.registerPatient('101', 'John', 54, 'B+')
waiting_room.registerPatient('102', 'Alice', 30, 'A-')
waiting_room.registerPatient('103', 'Bob', 45, 'O+')

# Display all patients
print("All Patients in the Waiting Room:")
waiting_room.showAllPatient()

# Serve a patient
waiting_room.servePatient()

# Display all patients after serving one
print("\nPatients Remaining in the Waiting Room:")
waiting_room.showAllPatient()

# Check if doctor can go home
waiting_room.canDoctorGoHome()

# Reverse the line
waiting_room.ReverseTheLine()

# Display all patients after reversing
print("\nPatients After Reversing the Line:")
waiting_room.showAllPatient()

# Cancel all appointments
waiting_room.cancelAll()

# Check if doctor can go home after canceling all appointments
waiting_room.canDoctorGoHome()


All Patients in the Waiting Room:
Patient ID: 101 Name: John Bloodgroup: B+
Patient ID: 102 Name: Alice Bloodgroup: A-
Patient ID: 103 Name: Bob Bloodgroup: O+
Serving patient: John

Patients Remaining in the Waiting Room:
Patient ID: 102 Name: Alice Bloodgroup: A-
Patient ID: 103 Name: Bob Bloodgroup: O+
No, doctor cannot go home.
Reverse successfull!

Patients After Reversing the Line:
Patient ID: 103 Name: Bob Bloodgroup: O+
Patient ID: 102 Name: Alice Bloodgroup: A-
All appointments canceled.
Yes, doctor can go home.


In [8]:
import numpy as np
arr=np.array([10,20,30,40,50])
new_arr=np.zeros(5,dtype=int)
for i in range(len(new_arr)):
    new_arr[i]=arr[i]
print(arr)
print('this is the new array')
print(new_arr)

[10 20 30 40 50]
this is the new array
[10 20 30 40 50]


how to turn multidimentinal array into array

In [18]:
arr = np.array([[2, 5, 1, 1], [6, 7, 1, 1], [1, 1, 1, 1]])
row,col=arr.shape
new_empty_arr=np.zeros(row*col)
for i in range(row):
    for j in range(col):
        output=arr[i][j]
    for k in range(len(new_empty_arr)):
        new_empty_arr[k]+=output
        # for k in range(len(new_empty_arr)):
            # new_empty_arr[k]+=arr[i][j]
print(arr)
# print(new_empty_arr)
print(output)

[[2 5 1 1]
 [6 7 1 1]
 [1 1 1 1]]
1


In [8]:
import numpy as np

arr = np.array([[2, 5, 1, 1], [6, 7, 1, 1], [1, 1, 1, 1]])

# Get the shape of the original array
row, col = arr.shape

# Initialize an empty list to store elements
new_empty_arr = []

# Iterate through each row
for i in range(row):
    # Iterate through each column
    for j in range(col):
        # Concatenate each element into the list
        new_empty_arr += [arr[i][j]]

# Convert the list to a numpy array
# new_array = np.array(new_empty_arr)

print("Original array:")
print(arr)

print("\nFlattened array using simple for loops without append():")
print(new_empty_arr)


Original array:
[[2 5 1 1]
 [6 7 1 1]
 [1 1 1 1]]

Flattened array using simple for loops without append():
[2, 5, 1, 1, 6, 7, 1, 1, 1, 1, 1, 1]


In [11]:
def convertArray(arr):
    row,col=arr.shape
    new_empty_arr=np.zeros(row*col,dtype=int)
    for i in range(row):
        for j in range(col):
            new_empty_arr+=arr[i][j]
arr = np.array([[2, 5, 1, 1], [6, 7, 1, 1], [1, 1, 1, 1]])
print(arr)
print(new_empty_arr)
convertArray(arr)

[[2 5 1 1]
 [6 7 1 1]
 [1 1 1 1]]
[2, 5, 1, 1, 6, 7, 1, 1, 1, 1, 1, 1]


In [34]:
#You are not allowed to edit in this cell
import numpy as np
class Node:
    def __init__(self, elem, next=None):
        self.elem, self.next = elem, next

def convertArray(arr):
    row,col=arr.shape
    new_empty_arr=np.zeros(row*col,dtype=int)
    for i in range(row):
        for j in range(col):
            new_empty_arr+=arr[i][j]
    return (new_empty_arr)

def createList(new_arr):  # creating the linked list from array
  head=Node(new_arr[0],None)
  temp=head
  for i in range(1,len(new_arr)):
    newNode=Node(new_arr[i],None)
    temp.next=newNode
    temp=temp.next
  return head

def printLinkedList(head):
    temp = head
    while temp != None:
        if temp.next != None:
            print(temp.elem, end='-->')
        else:
            print(temp.elem)
        temp = temp.next
    print()
matrix = np.array([[2, 8, 21],
                   [9, 6, 28],
                   [1, 8, 6],
                   [60, 42, 30]])
new_arr=convertArray(matrix)
printLinkedList(createList(new_arr))

221-->221-->221-->221-->221-->221-->221-->221-->221-->221-->221-->221



In [29]:
import numpy as np

class Node:
    def __init__(self, elem, next=None):
        self.elem, self.next = elem, next

def convertArray(arr):
    row, col = arr.shape
    new_empty_arr = np.zeros(row * col, dtype=int)
    index = 0
    for i in range(row):
        for j in range(col):
            new_empty_arr[index] = arr[i][j]
            index += 1
    return new_empty_arr

def createList(new_arr):  # creating the linked list from array
    head = Node(new_arr[0], None)
    temp = head
    for i in range(1, len(new_arr)):
        newNode = Node(new_arr[i], None)
        temp.next = newNode
        temp = temp.next  # move temp to the newly created node
    return head

def printLinkedList(head):
    temp = head
    while temp != None:
        if temp.next != None:
            print(temp.elem, end='-->')
        else:
            print(temp.elem)
        temp = temp.next
    print()

def sortedList(head): # sorting the linked list
  temp=head
  next_elem=temp.next
  # count=0
  # maxNum=0
  while temp!=None:
    if temp.elem<temp.next.elem:
      print(temp.elem)

matrix = np.array([[2, 8, 21],
                   [9, 6, 28],
                   [1, 8, 6],
                   [60, 42, 30]])
new_arr = convertArray(matrix)
printLinkedList(createList(new_arr))


2-->8-->21-->9-->6-->28-->1-->8-->6-->60-->42-->30



In [44]:
import numpy as np

class Node:
    def __init__(self, elem, next=None):
        self.elem, self.next = elem, next

def convertArray(arr):
    row, col = arr.shape
    new_empty_arr = np.zeros(row * col, dtype=int)
    index = 0
    for i in range(row):
        for j in range(col):
            new_empty_arr[index] = arr[i][j]
            index += 1
    return new_empty_arr

def createList(new_arr):  # creating the linked list from array
    head = Node(new_arr[0], None)
    temp = head
    for i in range(1, len(new_arr)):
        newNode = Node(new_arr[i], None)
        temp.next = newNode
        temp = temp.next  # move temp to the newly created node
    return head

def printLinkedList(head):
    temp = head
    while temp != None:
        if temp.next != None:
            print(temp.elem, end='-->')
        else:
            print(temp.elem)
        temp = temp.next
    print()

def sortedLinkedList(head):
    # if head is None:
    #     return head

    sorted_head = None
    current = head

    while current!=None:
        next_node = current.next    # next node stored
        if sorted_head==None or sorted_head.elem >= current.elem:
            current.next = sorted_head
            sorted_head = current
        else:
            current_head = sorted_head
            while current_head.next is not None and current_head.next.elem < current.elem:
                current_head = current_head.next
            current.next = current_head.next
            current_head.next = current
        current = next_node

    return sorted_head

matrix = np.array([[2, 8, 21],
                   [9, 6, 28],
                   [1, 8, 6],
                   [60, 42, 30]])
new_arr = convertArray(matrix)
head = createList(new_arr)
print("Original Linked List:")
printLinkedList(head)

sorted_head = sortedLinkedList(head)
print("\nSorted Linked List:")
printLinkedList(sorted_head)


Original Linked List:
2-->8-->21-->9-->6-->28-->1-->8-->6-->60-->42-->30


Sorted Linked List:
1-->2-->6-->6-->8-->8-->9-->21-->28-->30-->42-->60



In [18]:
def MatrixToLinkedListSort(matrix):
  #Write your code here
  # calling the functions
  h=createList(new_arr)
  
  # p=sortedList(h)
  # return p

# def sortedList(head): # sorting the linked list
#   temp=head
#   next_elem=temp.next
#   # count=0
#   # maxNum=0
#   while temp!=None:
#     if temp.elem<temp.next.elem:
#       print(temp.elem)
#You are not allowed to edit in this cell
#Driver Code
matrix = np.array([[2, 8, 21],
                   [9, 6, 28],
                   [1, 8, 6],
                   [60, 42, 30]])
Head = MatrixToLinkedListSort(matrix)
printLinkedList(Head) #This should print 1-->2-->6-->6-->8-->8-->9-->21-->28-->30-->42-->60

NameError: name 'new_arr' is not defined