Iteration

In [1]:
import numpy as np
def iteration(source):
    for i in range(len(source)):
        print(source[i])
arr=np.array([1,2,3,4,5])
iteration(arr)

1
2
3
4
5


Reverse Iteration

In [4]:
def reverseIteration(source):
    for i in range(len(arr)-1,-1,-1):
        print(source[i])
arr=np.array([1,2,3,4,5])
reverseIteration(arr)

5
4
3
2
1


Copy Array

In [10]:
def copyArray(source):
    # newArray=[None]*len(source)               [None,None,None,None,None]
    newArray=np.zeros(len(source),dtype=int)    #this also works---[0,0,0,0,0]
    for i in range(len(source)):
        newArray[i]=source[i]
    return newArray
arr=np.array([1,2,3,4,5])
print(copyArray(arr))

[1 2 3 4 5]


Resize Array

In [14]:
def resizeArray(oldArray,newCapacity):
    newArray=np.zeros(len(oldArray),dtype=int)
    for i in range(len(oldArray)):
        newArray[i]=oldArray[i]
    return newArray
arr=np.array([10,20,30,40,50])
resizeArray(arr,8)

array([10, 20, 30, 40, 50])

In [7]:
def resizeArray(oldArray,newCapacity):
    newArray=np.zeros(newCapacity,dtype=int)
    for i in range(len(oldArray)):
        newArray[i]=oldArray[i]
    return newArray
arr=np.array([10,20,30,40,50])
print(resizeArray(arr,8))


print("the old size was - 5")
print("the new size is now - 8")

[10 20 30 40 50  0  0  0]
the old size was - 5
the new size is now - 8


Left Shift

In [70]:
def leftShift(arr):
    for i in range(1,len(arr)):
        arr[i-1]=arr[i]
    arr[len(arr)-1]=0
    return arr
arr=np.array([1,2,3,4,5])
print(leftShift(arr))

[2 3 4 5 0]


In [24]:
def leftShiftAnywhere(arr,index):
    for i in range(index,len(arr)):
        arr[i-1]=arr[i]
    arr[len(arr)-1]=0
    return arr
arr=np.array([1,2,3,4,5])
leftShiftAnywhere(arr,4)

array([1, 2, 3, 5, 0])

Right Shift

In [69]:
def rightShift(arr):
    for i in range(len(arr)-1,0,-1):
        arr[i]=arr[i-1]
    arr[0]=0
    return arr
arr=np.array([1,2,3,4,5])
print(rightShift(arr))

[0 1 2 3 4]


Insert Element

What I understand by size---it's there to get rid of the error that you are gonna get if you assign the size's value more than or equal to the actual lenght of an array.
In this case, you can see: if size==len(arr) or size>len(arr): than show the message so that there's no error.
It also doesn't really matter that how much you are assigning to the size variable if it's inside 0-4. 5 or any other number will show the message.

In [68]:
def insertElement(arr,size,elem,index):
    if size==len(arr) or size>len(arr):
        print('No space left')
    else:
        for i in range(size,index,-1): 
            arr[i]=arr[i-1]
        arr[index]=elem
        return arr
arr=np.array([1,2,3,4,5])
print(insertElement(arr,1,30,3))

[ 1  2  3 30  5]


Doesn't even need a for loop let alone size. Don't know if it's the correct way of doing it but it appears so...

In [8]:
def insertElement(arr,size,elem,index):
    arr[index]=elem
    return arr
arr=np.array([1,2,3,4,5])
print(insertElement(arr,1,30,3))

[ 1  2  3 30  5]


Remove Element

In [138]:
def removeElement(arr,size,index):
    for i in range(size+1,index):
        arr[i-1]=arr[i]
    arr[index-1]=0
    return arr
arr=np.array([1,2,3,4,5])
print(removeElement(arr,5,3))

[1 2 0 4 5]


want to delete 3rd index

In [22]:
def removeElement(arr,size,index):
    arr[index]=0
    for i in range(index+1,len(arr)):
        arr[i-1]=arr[i]
    arr[len(arr)-1]=0
    return arr
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print("delete with left shitf:")
print(removeElement(arr,10,3))

[ 1  2  3  4  5  6  7  8  9 10]
delete with left shitf:
[ 1  2  3  5  6  7  8  9 10  0]


Left Rotate

In [140]:
def leftRotate(arr):
    store=arr[0]
    for i in range(1,len(arr)):
        arr[i-1]=arr[i]
    arr[len(arr)-1]=store
    return arr
arr=np.array([1,2,3,4,5])
print(leftRotate(arr))

[2 3 4 5 1]


Right Rotate

In [141]:
def leftRotate(arr):
    store=arr[len(arr)-1]
    for i in range(len(arr)-1,0,-1):
        arr[i]=arr[i-1]
    arr[0]=store
    return arr
arr=np.array([1,2,3,4,5])
print(leftRotate(arr))

[5 1 2 3 4]


Reverse Array --- Out of Place

In [24]:
def reverseArrayOutOfPlace(arr):
    revArr=np.zeros(len(arr),dtype=int)
    i=0
    j=len(arr)-1
    while i<len(arr):
        revArr[i]=arr[j]
        i+=1
        j-=1
    return revArr
arr=np.array([1,2,3,4,5])
print(reverseArrayOutOfPlace(arr))

[5 4 3 2 1]


Reverse --- In Place

In [155]:
def reverseArrayInPlace(arr):
    i=0
    j=len(arr)-1
    while i<j:
        temp=arr[i]
        arr[i]=arr[j]
        arr[j]=temp
        i+=1
        j-=1
    return arr
arr=np.array([1,2,3,4,5])
print(reverseArrayInPlace(arr))

[5 4 3 2 1]


In [169]:
def justReverse(arr):
    revArr1=np.zeros(len(arr),dtype=int)
    for i in range(len(arr)-1,-1,-1):
        # print(arr[i],end=',')
        revArr1[i]=arr[i]
    return revArr1
arr=np.array([1,2,3,4,5])
print(justReverse(arr))

[1 2 3 4 5]


find the lowest value

In [17]:
import numpy as np
def findLowestValue(arr):
    minVal=arr[0]
    for i in arr:
        if i<minVal:
            minVal=i
    print(minVal)
arr=np.array([7,12,9,4,11])
arr=np.array([85,12,9,4,2,11])
findLowestValue(arr)

2


find the highest value

In [22]:
import numpy as np
def findLowestValue(arr):
    maxValue=arr[0]
    for i in arr:
        if i>maxValue:
            maxValue=i
    print(maxValue)
# arr=np.array([7,12,9,4,11])
arr=np.array([85,12,9,4,2,11])
findLowestValue(arr)

85


Multidimentional Array

Creating an array

In [7]:
import numpy as np
def createArray():
    m=np.zeros((2,3),dtype=int)
    row=m.shape[0]
    col=m.shape[1]
    for i in range(row):
        for j in range(col):
            print(f'Enter element of [{i}][{j}] index: ')
            m[i][j]=int(input())
    return m
print(createArray())

Enter element of [0][0] index: 
Enter element of [0][1] index: 
Enter element of [0][2] index: 
Enter element of [1][0] index: 
Enter element of [1][1] index: 
Enter element of [1][2] index: 
[[100 200 300]
 [400 500 600]]


from class

In [13]:
def sumOfRow(arr):
    row=arr.shape[0]
    col=arr.shape[1]
    ans=np.zeros(row,dtype=int)
    for i in range(row):
        total=0
        for j in range(col):
            total+=arr[i][j]
    print(total)
arr = np.array([[2, 5, 1, 1], [6, 7, 1, 1], [1, 1, 1, 1]])
sumOfRow(arr)

4


In [16]:
def row_wise_sum(m):
    row, col = m.shape
    result = np.zeros((row, 1), dtype=int)
    for i in range(row):
        for j in range(col):
            result[i][0] += m[i][j]
    return result
arr = np.array([[2, 5, 1, 1], [6, 7, 1, 1], [1, 1, 1, 1]])
print(row_wise_sum(arr))

array([[ 9],
       [15],
       [ 4]])

In [19]:
def col_wise_sum(m):
    row, col = m.shape
    result = np.zeros((1, col), dtype=int)
    for i in range(col):
        for j in range(row):
            result[0][i] += m[j][i]
    return result
arr = np.array([[2, 5, 1, 1], [6, 7, 1, 1], [1, 1, 1, 1]])
print(col_wise_sum(arr))

array([[ 9, 13,  3,  3]])

In [2]:
import numpy as np
arr=np.zeros((3,5),dtype=int)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


interactively making a 2d array (partial because only creates 0 or 1)

In [56]:
import numpy as np
def creatingArray():
    x=int(input());y=int(input())
    for i in range(x):
        for j in range(y):
            arr=np.zeros((x,y),dtype=int)
    print(arr)
creatingArray()

[[0 0 0]
 [0 0 0]]


truely interactive

In [14]:
import numpy as np
def createTheArray():
    row=int(input('Row: '))
    col=int(input('Column: '))
    arr=np.zeros((row,col),dtype=int)
    for i in range(row):
        for j in range(col):
            arr[i][j]=int(input(f'Enter the elements: ({i},{j}): '))
    return arr
print(createTheArray())

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100  90  80  70  60]]


In [9]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Row Wise Iteration

In [18]:
def print_row(arr):
    row=arr.shape[0]
    col=arr.shape[1]
    for i in range(row):
        for j in range(col):
            print(arr[i][j],end=' ')
# arr=np.zeros((2,3),dtype=int)
arr=np.array([[1,2,3,4,5],[10,20,30,40,50],[100,90,80,70,60]])
print_row(arr)

1 2 3 4 5 10 20 30 40 50 100 90 80 70 60 

Column Wise Iteration

In [19]:
def print_row(arr):
    row=arr.shape[0]
    col=arr.shape[1]
    for i in range(col):
        for j in range(row):
            print(arr[j][i],end=' ')
# arr=np.zeros((2,3),dtype=int)
arr=np.array([[1,2,3,4,5],[10,20,30,40,50],[100,90,80,70,60]])
print_row(arr)

1 10 100 2 20 90 3 30 80 4 40 70 5 50 60 

Summation

In [24]:
def array_sum(arr):
    sum=0
    row=arr.shape[0]
    col=arr.shape[1]
    for i in range(row):
        for j in range(col):
            sum+=arr[i][j]
    return sum
arr=np.array([[1,2,3,4,5],[10,20,30,40,50]])
array_sum(arr)

165

Row Wise Sumation

In [37]:
import numpy as np
def row_wise_sum(arr):
    row=arr.shape[0]
    col=arr.shape[1]
    result=np.zeros((row,1),dtype=int)
    for i in range(row):
        for j in range(col):
            result[i][0]+=arr[i][j]
    return result
arr=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(row_wise_sum(arr))

[[ 15]
 [150]]


Column Wise Sum

In [43]:
import numpy as np
def column_wise_sum(ar):
    row=arr.shape[0]
    col=arr.shape[1]
    result=np.zeros((1,col),dtype=int)
    for i in range(col):
        for j in range(row):
            result[0][i]+=arr[j][i]
    return result
arr=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(column_wise_sum(arr))

[[11 22 33 44 55]]


Swapping

In [45]:
def swap_two_columns(arr):
    row=arr.shape[0]
    col=arr.shape[1]
    for i in range(row):
        arr[i][0],arr[i][1]=arr[i][1],arr[i][0]
    return arr
arr=np.array([[4,3],[2,5],[7,6]])
print(swap_two_columns(arr))

[[3 4]
 [5 2]
 [6 7]]


Swap Columns

In [46]:
def swap_columns(arr):
    row=arr.shape[0]
    col=arr.shape[1]
    for i in range(row):
        for j in range(col//2):
            arr[i][j],arr[i][col-1-j]=arr[i][col-1-j],arr[i][j]
    return arr
arr=np.array([[4,3,8],[2,5,-1],[-6,16,9],[4,13,11]])
print(swap_columns(arr))

[[ 8  3  4]
 [-1  5  2]
 [ 9 16 -6]
 [11 13  4]]


Addition

primary diagonal additionals

In [3]:
import numpy as np
def sum_primary_diagonal(arr):
    row=arr.shape[0]
    col=arr.shape[1]
    assert(row==col),'Not a square matrix'
    sum=0
    for i in range(row):
        sum+=arr[i][i]
    return sum
arr=np.array([[4,3,8],[2,5,1],[7,6,9]])
print(sum_primary_diagonal(arr))

18


secondary diagonal additionals

In [71]:
def sum_secondary_diagonal(array):
    row=array.shape[0]
    col=array.shape[1]
    assert(row==col),'Not a square matrix'
    sum=0
    for i in range(row):
        for j in range(col):
            if i+j==row-1:
               sum+=array[i][j] 
    return sum
# m=np.random.randint(9,size=(4,4))
# print(m)
array=np.array([[4,3,8],[2,5,1],[5,6,12]])
print(array)
print('')
print(sum_secondary_diagonal(array))

[[ 4  3  8]
 [ 2  5  1]
 [ 5  6 12]]

18


Add Two Matrixes (same direction)

In [2]:
def addMatrix(m,n):
    row_m=m.shape[0]
    col_m=m.shape[1]
    row_n=n.shape[0]
    col_n=n.shape[1]
    if row_m==row_n and col_m==col_n:
        print('Dimension mismatch')
    result=np.zeros((row_m,col_m),dtype=int)
    for i in range(row_m):
        for j in range(col_m):
            result[i][j]=m[i][j]+n[i][j]
    return result
m=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
n=np.array([[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(m)
print('+')
print(n)
print(addMatrix(m,n))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
+
[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
Dimension mismatch
[[17 19 21 23 25]
 [27 29 31 33 35]
 [37 39 41 43 45]]


Multiply two matrixes

In [46]:
def addMatrix(m,n):
    row_m=m.shape[0]
    col_m=m.shape[1]
    row_n=n.shape[0]
    col_n=n.shape[1]
    if col_m==row_n:
        print('Cannot multiply')
    result=np.zeros((row_m,col_n),dtype=int)
    for i in range(row_m):
        for j in range(col_n):
            for k in range(col_m):
                result[i][j]+=m[i][k]*n[k][j]
    return result
m=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
n=np.array([[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(addMatrix(m,n))

IndexError: index 3 is out of bounds for axis 0 with size 3

sum of two matrix

In [52]:
import random
import numpy as np
def add_matrix(m,n):
    row,col=m.shape
    result=np.zeros((row,col),dtype=int)
    for i in range(row):
        for j in range(col):
            result[i][j]=m[i][j]+n[i][j]
    return result
m=np.random.randint(9,size=(3,4))
n=np.random.randint(8,size=(3,4))
# print(add_matrix(m,n))
print(m)
print('+')
print(n)
print('Result:')
print(add_matrix(m,n))

[[3 6 4 1]
 [2 0 7 7]
 [3 4 0 4]]
+
[[5 3 0 6]
 [7 5 3 6]
 [5 7 1 6]]
Result:
[[ 8  9  4  7]
 [ 9  5 10 13]
 [ 8 11  1 10]]


Multiplication of two matrix

In [1]:
import numpy as np
import math
def multiply_matrix(m,n):
    row_m,col_m=m.shape
    row_n,col_n=n.shape
    if col_m==row_n:
        row,col=row_m,col_n
        result=np.zeros((row,col),dtype=int)
        for i in range(row):
            for j in range(col):
                for k in range(col_m):
                    result[i][j]+=m[i][k]*n[k][j]
        return result
m=np.random.randint(9,size=(3,4))
n=np.random.randint(8,size=(4,3))
print(m)
print('x')
print(n)
print('Result:')
print(multiply_matrix(m,n))

[[8 1 2 3]
 [2 1 2 1]
 [3 5 3 3]]
x
[[2 5 7]
 [3 1 7]
 [5 4 5]
 [5 0 2]]
Result:
[[44 49 79]
 [22 19 33]
 [51 32 77]]


Flip Vertical

In [12]:
def flip_vertical(matrix):
    row,col=matrix.shape
    for i in range(row//2):
        for j in range(col):
            temp=matrix[i][j]
            matrix[i][j]=matrix[row-1-i][j]
            matrix[row-1-i][j]=temp
    return matrix
m=np.random.randint(15,size=(4,4))
print('Current Matrix')
print(m)
print('')
print('Vertically flipped matrix')
print(flip_vertical(m))

Current Matrix
[[ 3 14  0  9]
 [ 9  4  0 12]
 [10 14  8  6]
 [12  0 10  8]]

Vertically flipped matrix
[[12  0 10  8]
 [10 14  8  6]
 [ 9  4  0 12]
 [ 3 14  0  9]]


Flip Horizontal

In [13]:
def flip_horizontal(matrix):
    row,col=matrix.shape
    for i in range(row):
        for j in range(col//2):
            temp=matrix[i][j]
            matrix[i][j]=matrix[i][col-1-j]
            matrix[i][col-1-j]=temp
    return matrix
m=np.random.randint(15,size=(4,4))
print('Current Matrix')
print(m)
print('')
print('Horizontally flipped matrix')
print(flip_horizontal(m))

Current Matrix
[[ 2 13 13  0]
 [ 1  9  7  3]
 [14  1  9 14]
 [ 4  5 12 12]]

Horizontally flipped matrix
[[ 0 13 13  2]
 [ 3  7  9  1]
 [14  9  1 14]
 [12 12  5  4]]


In [2]:
import numpy as np
def compress2Darray(arr):
  row,col=arr.shape
  result=np.zeros((2,2),dtype=int)
  for i in range(2):
    for j in range(2):
      if i ==0:
        start_row=0
        end_row=row//2
      elif i==1:
        start_row=row//2
        end_row=row
      if j==0:
        start_col=0
        end_col=col//2
      elif j==1:
        start_col=col//2
        end_col=col
      sum=0
      for r in range(start_row,end_row):
        for c in range(start_col,end_col):
          sum+=arr[r][c]
      result[i][j]=sum
  return result

# arr1=np.random.randint(15,size=(4,4))
arr1=np.array([[1,2,3,4],[5,6,7,8],[1,3,5,2],[-2,0,6,-3]])
print(arr1)
print(compress2Darray(arr1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  3  5  2]
 [-2  0  6 -3]]
[[14 22]
 [ 2 10]]


to print the output in a structured way

In [1]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))

finding the minimum value of a row in 2D array

In [27]:
import numpy as np
def findMin2D(arr):
    row,col=arr.shape
    print(minVal)
    for i in range(row):
        minVal=arr[i][0]
        for j in range(col):
            # print(arr[i][j])
            if arr[i][j]<minVal:
                minVal=arr[i][j]
        print(minVal)
arr=np.array([[10,2,3,4],[5,6,7,8],[4,9,3,2]])
findMin2D(arr)

UnboundLocalError: cannot access local variable 'minVal' where it is not associated with a value

Node and Linked List

Node class design

In [18]:
import numpy as np
class Node:
    def __init__(self,elem,next):
        self.elem=elem
        self.next=next

Creating a linked list

In [19]:
def createList(arr):
    head=Node(arr[0],None)
    tail=head
    for i in range(1,len(arr)):
        newNode=Node(arr[i],None)
        tail.next=newNode
        tail=tail.next
    return head
arr=np.array([1,2,3,4,5,6])
h=createList(arr)

Printing a list

In [20]:
def printList(head):
    current_node=head
    while current_node!=None:
        if current_node.next!=None:
            print(current_node.elem,end='--->')
        else:
            print(current_node.elem)
        current_node=current_node.next
    print()
arr=np.array([1,2,3,4,5,6])
h=createList(arr)
printList(h)

1--->2--->3--->4--->5--->6



Iteration over a linked list

In [49]:
def iteration(head):
    temp=head
    while temp!=None:
        print(temp.elem)
        temp=temp.next
arr=np.array([1,2,3,4,5,6]) # Defining an array
h=createList(arr) # Creating a Link List
h1=iteration(h) # Iterating through an array --- print is already happening inside the function

1
2
3
4
5
6


Count (finding the length of the linked list)

In [5]:
def countLinked(head):
    count=0
    temp=head
    while temp!=None:
        count+=1
        temp=temp.next
    return count
arr=np.array([1,2,3,4,5,6,7,8,9,10]) # Defining an array
h=createList(arr) # Creating a Link List
print(countLinked(h))

10


Node At

In [6]:
def nodeAt(head,idx):
    count=0
    temp=head
    obj=None
    while temp!=None:
        if count==idx:
            obj=temp
            break
        else:
            count+=1
        temp=temp.next
    if obj==None:
        print('Invalid index')
    else:
        return obj
h3=nodeAt(h,3)
print('main linked list:')
printList(h)
print('ML of the picked node:')
print(h3)
print('the value of the picked node:')
print(h3.elem)
print('ML of the next node:')
print(h3.next)
print('the value of the picked node:')
print(h3.next.elem)

main linked list:
1--->2--->3--->4--->5--->6--->7--->8--->9--->10

ML of the picked node:
the value of the picked node:
4
ML of the next node:
the value of the picked node:
5


Getting element of an specific index

In [7]:
def elemAt(head,idx):
    count=0
    temp=head
    while temp!=None:
        if temp.next!=None:
            if count==idx:
                return temp.elem
            temp=temp.next
            count+=1
        else:
            return f'Out of range. Index {idx} is unavailable'
    return None
arr=np.array([1,2,3,4,5,6,7,8,9,10]) # Defining an array
h=createList(arr) # Creating a Link List
print('the element is at index no.:')
elemAt(h,4)
# elemAt(h,10)

the element is at index no.:


5

Setting new element of an specific index (Replacing a value)

In [8]:
def setIdx(head,idx,elem):
    count=0
    current_node=head
    isUpdated=False
    while current_node!=None:
        if count==idx:
            current_node.elem=elem
            isUpdated=True
            break
        current_node=current_node.next
        count+=1
    if isUpdated:
        print('Value successfully updated!')
    else:
        print('Invalid index')
arr1=np.array([1,2,3,4,5,6,7,8,9,10]) # Defining an array
modh=createList(arr1) # Creating a Link List
setIdx(modh,4,16)
printList(modh)

Value successfully updated!
1--->2--->3--->4--->16--->6--->7--->8--->9--->10



Getting index of an specific element (will search from the linked list)

In [12]:
def indexOf(head,elem):
    current_node=head
    count=0
    while current_node!=None:
        if current_node.elem==elem:
            return count
        count+=1
        current_node=current_node.next
    return f'There is not such element in the linked list'
arr=np.array([10,20,53,84,75,76,97,21,90,15]) # Defining an array
mod_h=createList(arr) # Creating a Link List
print(indexOf(mod_h,85))
print(indexOf(mod_h,84))
# printList(h)

There is not such element in the linked list
3


Contains the element or not in the linked list (True or False)

In [18]:
def contains(head,elem):
    current_node=head
    while current_node!=None:
        if current_node.elem==elem:
            return True
        current_node=current_node.next
    return False
arr=np.array([1,2,3,4,5,6,7,8,9,10]) # Defining an array
h=createList(arr) # Creating a Link List
print(contains(h,5))
printList(h)

True
1--->2--->3--->4--->5--->6--->7--->8--->9--->10



In [19]:
printList(h)

1--->2--->3--->4--->5--->6--->7--->8--->9--->10



Inserting an element in the linked list

In [20]:
def insert(head,elem,idx):
    current_node=head
    j=0
    while j!=idx:
        current_node=current_node.next
        j+=1
    newNode=Node(elem,None)
    current_node.next=newNode
    return head
h2=insert(h,30,5)
printList(h2)

1--->2--->3--->4--->5--->6--->30



In [21]:
def insert(head,idx,elem):
    count=0
    current_node=head
    isUpdated=False
    while current_node!=None:
        if count==idx:
            current_node.elem=elem
            isUpdated=True
            break
        current_node=current_node.next
        count+=1
    if isUpdated:
        print('Value successfully updated!')
    else:
        print('Invalid index')
arr=np.array([1,2,3,4,5,6,7,8,9,10]) # Defining an array
h=createList(arr) # Creating a Link List
insert(h,4,16)
printList(h)

Value successfully updated!
1--->2--->3--->4--->16--->6--->7--->8--->9--->10



Remove an element by it's index number

In [ ]:
def remove(head,idx):
    if idx==0:
        head=head.next
    elif idx>1 and idx<countLinked(head):
        n1=nodeAt

Copy the linked list

In [34]:
def copyList(source):
    copy_head=None
    copy_tail=None
    current_node=source
    while current_node!=None:
        newNode=Node(current_node.elem,None)
        if copy_head==None:
            copy_head=newNode
            copy_tail=copy_head
        else:
            copy_tail.next=newNode
            copy_tail=copy_tail.next
        current_node=current_node.next
    return copy_head
print('main linked list:')
printList(h)
print('ML of original LL:')
print(h)
print('Original linked list:')
h4=copyList(h) # ---> only this line is needed for this code, other lines are for just background check
printList(h4)
print('Copied linked list')
print('ML of the copied LL:')
print(f'{h4}    <---this changes')
printList(h4)

main linked list:
1--->2--->3--->4--->16--->6--->7--->8--->9--->10

ML of original LL:
Original linked list:
1--->2--->3--->4--->16--->6--->7--->8--->9--->10

Copied linked list
ML of the copied LL:
<__main__.Node object at 0x000002CE4E1879B0>    <---this changes
1--->2--->3--->4--->16--->6--->7--->8--->9--->10



--------insert--------append--------prepend--------remove--------

In [35]:
printList(h)

1--->2--->3--->4--->16--->6--->7--->8--->9--->10



Insert

In [39]:
def insert(head,idx,elem):
    count=0
    temp=head
    while count!=idx:
        temp=temp.next
        count+=1
    newNode=Node(elem,None)
    newNode=newNode.next
    temp.next=newNode
    return head
printList(insert(h,4,25))

In [26]:
def insert(head,idx,elem):
    total_nodes=countLinked(head)
    if idx==0:
        n=Node(elem,head)
        head=n
    elif idx>1 and idx<total_nodes:
        n=Node(elem,head)
        n1=nodeAt(head,idx-1)
        n2=nodeAt(head,idx)
        n.next=n2
        n1.next=n
    elif idx==total_nodes:
        n=Node(elem,None)
        n1.nodeAt(head,total_nodes-1)
        n1.next=n
    else:
        print('Invalid Index')
    return head
print('main list:')
printList(h)
# # v=insert(h,4,105)
# v=insert(h,9,2090)
# printList(v)

main list:
1--->2--->3--->4--->5--->6



Reverse

reverse out-of-place

In [27]:
def reverse_out_of_place(head):
  new_head = Node(head.elem, None)
  temp = head.next
  while temp != None:
    n = Node(temp.elem, new_head)
    new_head = n
    temp = temp.next
  return new_head
v=reverse_out_of_place(h)
printList(v)

6--->5--->4--->3--->2--->1

